import type { Metadata } from "next";
import { Inter } from "next/font/google";
import  { Toaster } from 'react-hot-toast';
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Anonymous message",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>{children}
          <Toaster/>
        </body>
      </AuthProvider>
    </html>
  );
}
