const data = [
    "What's a book that has changed your perspective on life?",
    "If you could have dinner with any historical figure, who would it be and why?",
    "What's a hobby you've always wanted to pick up but haven't yet?",
    "What's the most beautiful place you've ever visited and why?",
    "If you could live in any fictional universe, which one would you choose and why?",
    "What's a random act of kindness you experienced recently?",
    "If you could master one skill instantly, what would it be?",
    "What's the best piece of advice you've ever received?",
    "If you could time travel, would you go to the past or the future, and why?",
    "What's your favorite way to unwind after a long day?",
    "What's a goal you have for the next year?",
    "If you could invent anything, what would it be?",
    "What's the most memorable meal you've ever had?",
    "What's a movie that always makes you laugh no matter how many times you watch it?",
    "If you could swap lives with anyone for a day, who would it be and why?",
    "What's your favorite season and what do you love about it?",
    "If you could speak any language fluently, which one would you choose and why?",
    "What's a tradition or holiday that means a lot to you?",
    "What's your favorite thing about your hometown?",
    "What's an accomplishment you're really proud of?",
    "If you could have any animal as a pet, what would it be and why?",
    "What's a project or activity that always puts you in a good mood?",
    "What's the most interesting thing you've learned recently?",
    "If you could see any band or artist live, who would it be and why?",
    "What's your favorite way to spend a weekend?",
    "If you could only eat one type of cuisine for the rest of your life, what would it be?",
    "What's a TV show you think everyone should watch?",
    "If you could have any superpower, what would it be and why?",
    "What's your favorite childhood memory?",
    "If you could change one thing about the world, what would it be?",
    "What's a skill you wish more people took the time to learn?",
    "What's the most interesting place you've traveled to?",
    "If you could have a conversation with your future self, what would you ask?",
    "What's something you've always wanted to learn but haven't yet?",
    "If you could design your dream home, what would it look like?",
    "What's the best compliment you've ever received?",
    "If you could create a holiday, what would it celebrate and how would people observe it?",
    "What's a habit you admire in others?",
    "If you could relive one moment from your past, what would it be and why?",
    "What's your favorite way to get creative?",
    "If you could have any job in the world, what would it be?",
    "What's a book or movie that left a lasting impression on you?",
    "What's something that always brings a smile to your face?",
    "If you could host a talk show, who would be your first guest and why?",
    "What's a piece of music that moves you deeply?",
    "If you could live anywhere in the world, where would it be and why?",
    "What's your favorite outdoor activity?",
    "If you could witness any event in history, what would it be?",
    "What's a topic you could talk about for hours?",
    "If you could change one thing about yourself, what would it be and why?",
    "What's a fun fact that not many people know about you?",
    "If you could have a meal with any three people, living or dead, who would you choose?",
    "What's your favorite way to stay active?",
    "If you could learn the truth about one mystery, what would it be?",
    "What's a dream you've had that you hope to achieve one day?",
    "If you could play any musical instrument, which one would you choose?",
    "What's your favorite way to relax and recharge?",
    "If you could be any character from a book or movie, who would you be and why?",
    "What's something you're passionate about and why?",
    "If you could make a documentary, what would it be about?",
    "What's a recipe you love to cook for others?",
    "If you could redesign your country's flag, what would it look like?",
    "What's a cause or charity you support and why?",
    "If you could have any piece of art in your home, what would it be?",
    "What's your favorite way to spend a rainy day?",
    "If you could go on a road trip with anyone, who would it be and where would you go?",
    "What's a life lesson you think everyone should learn?",
    "If you could write a book, what genre would it be and what would it be about?",
    "What's your favorite thing to do when you need some alone time?",
    "If you could start a business, what would it be and why?",
    "What's a memory that makes you laugh every time you think about it?",
    "If you could switch places with any fictional character for a day, who would it be and why?",
    "What's your favorite way to show kindness to others?",
    "If you could visit any country, which one would it be and why?",
    "What's a goal you've set for yourself recently?",
    "If you could experience any profession for a week, what would it be?",
    "What's something you find inspiring?",
    "If you could have any famous artwork in your home, which one would you choose?",
    "What's your favorite way to celebrate a special occasion?",
    "If you could have a conversation with anyone from history, who would it be and why?",
    "What's a question you've always wanted to ask someone but never did?",
    "If you could travel back in time, which period would you visit and why?",
    "What's your favorite way to stay healthy?",
    "If you could redesign the human body, what feature would you add?",
    "What's a book you think everyone should read?",
    "If you could create a new invention, what problem would it solve?",
    "What's something you do to make others feel welcome?",
    "If you could witness any natural phenomenon, what would it be?",
    "What's a song that always lifts your spirits?",
    "If you could be any animal for a day, what would you be and why?",
    "What's a skill you think everyone should have?",
    "If you could visit any planet, which one would you choose and why?",
    "What's your favorite way to spend time with friends?",
    "If you could change one thing about society, what would it be?",
    "What's a quote that inspires you?",
    "If you could create a new sport, what would it be like?",
    "What's a challenge you've overcome that you're proud of?",
    "If you could have any job for a day, what would it be?",
    "What's something you're curious about and want to learn more of?",
    "If you could plan the perfect day, what activities would it include?"
];

export default data;

